/******************************************************************************\
 * Name: application.ts
 *
 * Purpose: Class to start up the server.
 *          Note this file was auto-generated by the LoopBack CLI scaffolding.
 *
 * Author: naasse (nate.asselstine@gmail.com)
 \******************************************************************************/

import {BootMixin} from "@loopback/boot";
import {ApplicationConfig} from "@loopback/core";
import {RestExplorerBindings, RestExplorerComponent,} from "@loopback/rest-explorer";
import {RepositoryMixin} from "@loopback/repository";
import {MiddlewareSequence, RestApplication} from "@loopback/rest";
import {ServiceMixin} from "@loopback/service-proxy";
import path from "path";

export {ApplicationConfig};

export class ApiApplication extends BootMixin(
    ServiceMixin(RepositoryMixin(RestApplication))
) {
    constructor(options: ApplicationConfig = {}) {
        super(options);

        // Set up the standard sequence.
        this.sequence(MiddlewareSequence);

        // Set up default home page
        this.static("/", path.join(__dirname, "../public"));

        // Customize @loopback/rest-explorer configuration here
        this.configure(RestExplorerBindings.COMPONENT).to({
            path: "/explorer",
        });
        this.component(RestExplorerComponent);

        this.projectRoot = __dirname;
        // Customize @loopback/boot Booter Conventions here
        this.bootOptions = {
            "controllers": {
                // Customize ControllerBooter Conventions here
                "dirs": ["controllers"],
                "extensions": [".controller.js"],
                "nested": true
            }
        };
    }
}
