/******************************************************************************\
 * Name: openapi-spec.ts
 *
 * Purpose: Export the Open API specification based on the LoopBack
 *          discoverable API routes.
 *          Note this file was auto-generated by the LoopBack CLI scaffolding.
 *
 * Author: naasse (nate.asselstine@gmail.com)
 \******************************************************************************/

import {ApplicationConfig} from "@loopback/core";
import {ApiApplication} from "./application";

/**
 * Export the OpenAPI spec from the application
 */
async function exportOpenApiSpec(): Promise<void> {
    const config: ApplicationConfig = {
        "rest": {
            "port": +(process.env.PORT ?? 3000),
            "host": process.env.HOST ?? "localhost"
        }
    };
    const outFile = process.argv[2] ?? "";
    const app = new ApiApplication(config);
    await app.boot();
    await app.exportOpenApiSpec(outFile);
}

exportOpenApiSpec().catch(err => {
    console.error("Failed to export OpenAPI spec from the application.", err);
    process.exit(1);
});
